# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a5511492e56c618f5a3556ec7f2ae8950b856e92541cc0667a50487b390883540e433803b4bc00844c5a16cb029f968df815f449f9eb87c3d58d81687d8c20a

test:
  secret_key_base: 63dbe01bbe3749e18d9712e81ba80158c0c80062c98238c78f29ded7229eef4d1e2e59a1c8a6d43f6dccd637dc74f629620b5f47c5798f71c00b78ec1780e620

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
